# Generated by Django 4.0.4 on 2022-05-03 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
