# Generated by Django 4.0.4 on 2022-05-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chocolates',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
